# Generated by Django 5.2.12 on 2026-03-21 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom de l'examen"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code unique pour accéder à cet examen (ex: BAC2025-CM)",
                        max_length=50,
                        unique=True,
                        verbose_name="Code d'accès",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Année")),
                (
                    "passing_grade",
                    models.FloatField(default=10.0, verbose_name="Seuil de réussite"),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=False, verbose_name="Verrouillé"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Examen",
                "verbose_name_plural": "Examens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Code"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Établissement",
                "verbose_name_plural": "Établissements",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom de la salle"),
                ),
                ("capacity", models.IntegerField(verbose_name="Capacité")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="exams.exam",
                        verbose_name="Examen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salle",
                "verbose_name_plural": "Salles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidate_number",
                    models.CharField(max_length=20, verbose_name="N° Candidat"),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        default="",
                        max_length=1,
                        verbose_name="Sexe",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "is_absent",
                    models.BooleanField(default=False, verbose_name="Absent"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="exams.exam",
                        verbose_name="Examen",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="exams.school",
                        verbose_name="Établissement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élève",
                "verbose_name_plural": "Élèves",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="RoomAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seat_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="N° de place"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="exams.room",
                        verbose_name="Salle",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_assignment",
                        to="exams.student",
                        verbose_name="Élève",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignation",
                "verbose_name_plural": "Assignations",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nom de l'épreuve"),
                ),
                (
                    "coefficient",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Coefficient"
                    ),
                ),
                (
                    "max_score",
                    models.FloatField(default=20.0, verbose_name="Note maximale"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="exams.exam",
                        verbose_name="Examen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Épreuve",
                "verbose_name_plural": "Épreuves",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(verbose_name="Note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="exams.student",
                        verbose_name="Élève",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="exams.subject",
                        verbose_name="Épreuve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
            },
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["exam"], name="exams_room_exam_id_5eff18_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["exam"], name="exams_stude_exam_id_f5065f_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["school"], name="exams_stude_school__2bfca7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="exams_stude_last_na_782a84_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("exam", "candidate_number")},
        ),
        migrations.AddIndex(
            model_name="roomassignment",
            index=models.Index(fields=["room"], name="exams_rooma_room_id_b85e8f_idx"),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["exam"], name="exams_subje_exam_id_c121f9_idx"),
        ),
        migrations.AddIndex(
            model_name="score",
            index=models.Index(
                fields=["student"], name="exams_score_student_4309ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="score",
            index=models.Index(
                fields=["subject"], name="exams_score_subject_ae136d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="score",
            constraint=models.UniqueConstraint(
                fields=("student", "subject"), name="unique_score_per_student_subject"
            ),
        ),
    ]
