# Generated by Django 5.2.12 on 2026-04-22 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'examen")),
                ('code', models.CharField(blank=True, default='', help_text='Code unique pour accéder à cet examen (ex: BAC2025-CM). Laisser vide pour génération automatique.', max_length=50, unique=True, verbose_name="Code d'accès")),
                ('year', models.IntegerField(verbose_name='Année')),
                ('exam_type', models.CharField(choices=[('BAC', 'BAC'), ('BEPC', 'BEPC'), ('CAP', 'CAP'), ('PROBATOIRE', 'Probatoire'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name="Type d'examen")),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name="Lieu / centre d'examen")),
                ('grading_scale', models.FloatField(default=20.0, help_text='Échelle des moyennes et du seuil (ex. 20 pour le bac, 10 pour un contrôle). Les notes par épreuve restent sur leur propre note max.', verbose_name='Barème (note max de référence)')),
                ('passing_grade', models.FloatField(default=10.0, verbose_name='Seuil de réussite')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Verrouillé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('code', models.CharField(blank=True, default='', max_length=50, verbose_name='Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nom')),
                ('code', models.CharField(help_text='Identifiant unique pour la connexion à l’interface correction.', max_length=64, unique=True, verbose_name='Code correcteur')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Téléphone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la salle')),
                ('capacity', models.IntegerField(verbose_name='Capacité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='exams.exam', verbose_name='Examen')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_number', models.CharField(max_length=20, verbose_name='N° Candidat')),
                ('first_name', models.CharField(max_length=255, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nom')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], default='', max_length=1, verbose_name='Sexe')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('is_absent', models.BooleanField(default=False, verbose_name='Absent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='exams.exam', verbose_name='Examen')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='exams.school', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(blank=True, null=True, verbose_name='N° de place')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.room', verbose_name='Salle')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignment', to='exams.student', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Assignation',
                'verbose_name_plural': 'Assignations',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'épreuve")),
                ('coefficient', models.FloatField(blank=True, null=True, verbose_name='Coefficient')),
                ('max_score', models.FloatField(default=20.0, verbose_name='Note maximale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='exams.exam', verbose_name='Examen')),
            ],
            options={
                'verbose_name': 'Épreuve',
                'verbose_name_plural': 'Épreuves',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='exams.student', verbose_name='Élève')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='exams.subject', verbose_name='Épreuve')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Harmonization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('ADD', 'Ajout de points'), ('MULTIPLY', 'Coefficient multiplicateur'), ('SET_MIN', 'Note plancher')], max_length=16, verbose_name='Type d’ajustement')),
                ('value', models.FloatField(verbose_name='Valeur (points, coefficient ou plancher)')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Date d’application')),
                ('is_applied', models.BooleanField(default=False, verbose_name='Appliqué')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harmonizations_applied', to=settings.AUTH_USER_MODEL, verbose_name='Appliqué par')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harmonizations', to='exams.exam', verbose_name='Examen')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harmonizations', to='exams.subject', verbose_name='Épreuve')),
            ],
            options={
                'verbose_name': 'Harmonisation',
                'verbose_name_plural': 'Harmonisations',
                'ordering': ['-applied_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lead_corrector', models.BooleanField(default=False, verbose_name='Correcteur principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='exams.exam', verbose_name='Examen')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='exams.subject', verbose_name='Épreuve')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='exams.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Assignation épreuve',
                'verbose_name_plural': 'Assignations épreuves',
            },
        ),
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.FloatField(blank=True, help_text='Vide pour la première saisie.', null=True, verbose_name='Ancienne note')),
                ('new_value', models.FloatField(verbose_name='Nouvelle note')),
                ('reason', models.CharField(choices=[('INITIAL', 'Saisie initiale'), ('CORRECTION', 'Correction'), ('RECORRECTION', 'Re-correction'), ('HARMONIZATION', 'Harmonisation')], max_length=32, verbose_name='Motif')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='exams.score', verbose_name='Note')),
                ('changed_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_history_entries', to='exams.teacher', verbose_name='Correcteur')),
            ],
            options={
                'verbose_name': 'Historique de note',
                'verbose_name_plural': 'Historiques de notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['exam'], name='exams_room_exam_id_5eff18_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['exam'], name='exams_stude_exam_id_f5065f_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school'], name='exams_stude_school__2bfca7_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name', 'first_name'], name='exams_stude_last_na_782a84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('exam', 'candidate_number')},
        ),
        migrations.AddIndex(
            model_name='roomassignment',
            index=models.Index(fields=['room'], name='exams_rooma_room_id_b85e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['exam'], name='exams_subje_exam_id_c121f9_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['student'], name='exams_score_student_4309ac_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['subject'], name='exams_score_subject_ae136d_idx'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('student', 'subject'), name='unique_score_per_student_subject'),
        ),
        migrations.AddIndex(
            model_name='harmonization',
            index=models.Index(fields=['exam', 'subject'], name='exams_harmo_exam_id_94c2eb_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectassignment',
            index=models.Index(fields=['exam'], name='exams_subje_exam_id_be63d5_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectassignment',
            index=models.Index(fields=['teacher'], name='exams_subje_teacher_bee82f_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectassignment',
            index=models.Index(fields=['subject'], name='exams_subje_subject_87c59d_idx'),
        ),
        migrations.AddConstraint(
            model_name='subjectassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject'), name='unique_teacher_subject_assignment'),
        ),
        migrations.AddIndex(
            model_name='scorehistory',
            index=models.Index(fields=['score'], name='exams_score_score_i_d00a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='scorehistory',
            index=models.Index(fields=['created_at'], name='exams_score_created_eebd0a_idx'),
        ),
    ]
