# Generated by Django 5.2.12 on 2026-03-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='exam',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('BAC', 'BAC'), ('BEPC', 'BEPC'), ('CAP', 'CAP'), ('PROBATOIRE', 'Probatoire'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name="Type d'examen"),
        ),
        migrations.AddField(
            model_name='exam',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Lieu / centre d'examen"),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
    ]
