# Generated by Django 5.2.12 on 2026-04-22 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du forfait')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tagline', models.CharField(blank=True, default='', max_length=200, verbose_name='Accroche')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('price_fcfa', models.PositiveIntegerField(blank=True, help_text='Laisser vide pour gratuit ou sur devis.', null=True, verbose_name='Prix (FCFA)')),
                ('billing_period', models.CharField(choices=[('FREE', 'Gratuit'), ('MONTHLY', 'Par mois'), ('YEARLY', 'Par an'), ('CUSTOM', 'Sur devis')], default='MONTHLY', max_length=16, verbose_name='Période de facturation')),
                ('max_exams', models.PositiveIntegerField(blank=True, help_text='Vide = illimité.', null=True, verbose_name="Nb max d'examens")),
                ('max_students_per_exam', models.PositiveIntegerField(blank=True, help_text='Vide = illimité.', null=True, verbose_name='Nb max de candidats / examen')),
                ('max_teachers', models.PositiveIntegerField(blank=True, help_text='Vide = illimité.', null=True, verbose_name='Nb max de correcteurs')),
                ('features', models.JSONField(blank=True, default=list, help_text='Liste de chaînes affichées sur la page tarifs.', verbose_name='Fonctionnalités incluses')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Forfait',
                'verbose_name_plural': 'Forfaits',
                'ordering': ['sort_order', 'price_fcfa'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, default='', max_length=255, verbose_name='Organisation')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Téléphone')),
                ('subscription_start', models.DateField(blank=True, null=True, verbose_name='Début abonnement')),
                ('subscription_end', models.DateField(blank=True, null=True, verbose_name='Fin abonnement')),
                ('is_subscription_active', models.BooleanField(default=True, verbose_name='Abonnement actif')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='exams.plan', verbose_name='Forfait')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
