# Generated by Django 5.2.12 on 2026-03-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_enriched_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Code unique pour accéder à cet examen (ex: BAC2025-CM). Laisser vide pour génération automatique.', max_length=50, unique=True, verbose_name="Code d'accès"),
        ),
    ]
