# Generated by Django 5.2.12 on 2026-03-22 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_grading_scale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nom')),
                ('code', models.CharField(help_text='Identifiant unique pour la connexion à l’interface correction.', max_length=64, unique=True, verbose_name='Code correcteur')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Téléphone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Harmonization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('ADD', 'Ajout de points'), ('MULTIPLY', 'Coefficient multiplicateur'), ('SET_MIN', 'Note plancher')], max_length=16, verbose_name='Type d’ajustement')),
                ('value', models.FloatField(verbose_name='Valeur (points, coefficient ou plancher)')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Date d’application')),
                ('is_applied', models.BooleanField(default=False, verbose_name='Appliqué')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harmonizations_applied', to=settings.AUTH_USER_MODEL, verbose_name='Appliqué par')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harmonizations', to='exams.exam', verbose_name='Examen')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harmonizations', to='exams.subject', verbose_name='Épreuve')),
            ],
            options={
                'verbose_name': 'Harmonisation',
                'verbose_name_plural': 'Harmonisations',
                'ordering': ['-applied_at', '-id'],
                'indexes': [models.Index(fields=['exam', 'subject'], name='exams_harmo_exam_id_94c2eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lead_corrector', models.BooleanField(default=False, verbose_name='Correcteur principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='exams.exam', verbose_name='Examen')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='exams.subject', verbose_name='Épreuve')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='exams.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Assignation épreuve',
                'verbose_name_plural': 'Assignations épreuves',
                'indexes': [models.Index(fields=['exam'], name='exams_subje_exam_id_be63d5_idx'), models.Index(fields=['teacher'], name='exams_subje_teacher_bee82f_idx'), models.Index(fields=['subject'], name='exams_subje_subject_87c59d_idx')],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'subject'), name='unique_teacher_subject_assignment')],
            },
        ),
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.FloatField(blank=True, help_text='Vide pour la première saisie.', null=True, verbose_name='Ancienne note')),
                ('new_value', models.FloatField(verbose_name='Nouvelle note')),
                ('reason', models.CharField(choices=[('INITIAL', 'Saisie initiale'), ('CORRECTION', 'Correction'), ('RECORRECTION', 'Re-correction'), ('HARMONIZATION', 'Harmonisation')], max_length=32, verbose_name='Motif')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='exams.score', verbose_name='Note')),
                ('changed_by_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_history_entries', to='exams.teacher', verbose_name='Correcteur')),
            ],
            options={
                'verbose_name': 'Historique de note',
                'verbose_name_plural': 'Historiques de notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['score'], name='exams_score_score_i_d00a9c_idx'), models.Index(fields=['created_at'], name='exams_score_created_eebd0a_idx')],
            },
        ),
    ]
